# Generated by Django 3.1.6 on 2021-02-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('hint1', models.CharField(max_length=255)),
                ('hint2', models.CharField(max_length=255)),
                ('hint3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParadoxUser',
            fields=[
                ('google_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('ref_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=255, unique=True)),
                ('ref_success', models.IntegerField()),
                ('google_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.paradoxuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_time', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('attempts', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=100)),
                ('super_coins', models.IntegerField()),
                ('google_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.paradoxuser')),
            ],
        ),
    ]
