# Generated by Django 3.1.6 on 2021-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210203_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='super_coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='ref_success',
            field=models.IntegerField(default=0),
        ),
    ]
