# Generated by Django 3.1.6 on 2021-02-03 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20210203_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='id',
        ),
        migrations.AlterField(
            model_name='paradoxuser',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Minimum Length should be 3 Characters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.paradoxuser', unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.paradoxuser', unique=True),
        ),
    ]
